const mockGroup = [
  { name: 'Staff Scientist' },
  { name: 'Design Engineer' },
  { name: 'Cost Accountant' },
  { name: 'Geologist III' },
  { name: 'Automation Specialist I' },
  { name: 'Junior Executive' },
  { name: 'Human Resources Assistant III' },
  { name: 'Senior Editor' },
  { name: 'Account Executive' },
  { name: 'Financial Analyst' },
  { name: 'Financial Advisor' },
  { name: 'Help Desk Operator' },
  { name: 'Senior Developer' },
  { name: 'Structural Engineer' },
  { name: 'Pharmacist' },
  { name: 'Speech Pathologist' },
  { name: 'Analyst Programmer' },
  { name: 'Senior Financial Analyst' },
  { name: 'Help Desk Technician' },
  { name: 'Director of Sales' },
  { name: 'Accountant III' },
  { name: 'Software Consultant' },
  { name: 'Product Engineer' },
  { name: 'Account Representative I' },
  { name: 'Biostatistician II' },
  { name: 'Data Coordiator' },
  { name: 'Desktop Support Technician' },
  { name: 'Operator' },
  { name: 'Office Assistant IV' },
  { name: 'Administrative Officer' },
  { name: 'Analog Circuit Design manager' },
  { name: 'Payment Adjustment Coordinator' },
  { name: 'Senior Cost Accountant' },
  { name: 'Internal Auditor' },
  { name: 'Web Developer IV' },
  { name: 'Chief Design Engineer' },
  { name: 'Chemical Engineer' },
  { name: 'Quality Control Specialist' },
  { name: 'Nurse' },
  { name: 'Sales Associate' },
  { name: 'Paralegal' },
  { name: 'Nuclear Power Engineer' },
  { name: 'Physical Therapy Assistant' },
  { name: 'Engineer IV' },
  { name: 'Accounting Assistant IV' },
  { name: 'Marketing Manager' },
  { name: 'Environmental Specialist' },
  { name: 'Assistant Media Planner' },
  { name: 'Account Representative IV' },
  { name: 'Quality Engineer' },
  { name: 'Nurse Practicioner' },
  { name: 'Staff Accountant II' },
  { name: 'Computer Systems Analyst IV' },
  { name: 'Legal Assistant' },
  { name: 'VP Quality Control' },
  { name: 'Human Resources Assistant II' },
  { name: 'Registered Nurse' },
  { name: 'Safety Technician I' },
  { name: 'Social Worker' },
  { name: 'Business Systems Development Analyst' },
  { name: 'Account Coordinator' },
  { name: 'Environmental Tech' },
  { name: 'Developer II' },
  { name: 'Health Coach II' },
  { name: 'Research Nurse' },
  { name: 'Geologist I' },
  { name: 'Tax Accountant' },
  { name: 'Computer Systems Analyst I' },
  { name: 'Technical Writer' },
  { name: 'Dental Hygienist' },
  { name: 'Sales Representative' },
  { name: 'Systems Administrator II' },
  { name: 'Senior Quality Engineer' },
  { name: 'Media Manager III' },
  { name: 'Geological Engineer' },
];

module.exports = mockGroup;
